/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AESboxJNI */

#ifndef _Included_AESboxJNI
#define _Included_AESboxJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AESboxJNI
 * Method:    Encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_AESboxJNI_Encrypt
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     AESboxJNI
 * Method:    Decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_AESboxJNI_Decrypt
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
