/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aiss_aesBox_AESboxJNI */

#ifndef _Included_aiss_aesBox_AESboxJNI
#define _Included_aiss_aesBox_AESboxJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef aiss_aesBox_AESboxJNI_ENCRYPT
#define aiss_aesBox_AESboxJNI_ENCRYPT 1L
#undef aiss_aesBox_AESboxJNI_DECRYPT
#define aiss_aesBox_AESboxJNI_DECRYPT 2L
/*
 * Class:     aiss_aesBox_AESboxJNI
 * Method:    Encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aiss_aesBox_AESboxJNI_Encrypt
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     aiss_aesBox_AESboxJNI
 * Method:    Decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aiss_aesBox_AESboxJNI_Decrypt
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
