/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aiss_aes_AESCall */

#ifndef _Included_aiss_aes_AESCall
#define _Included_aiss_aes_AESCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aiss_aes_AESCall
 * Method:    aes
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_aiss_aes_AESCall_aes
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
